### ISSUE TITLE
watchdog: pgrep statt ps 

### ISSUE THREAD

**Issue by rubo77** [freifunk-stuttgart/Gluon-Packages#2]
https://github.com/freifunk-stuttgart/Gluon-Packages/blob/c22cea54014470b0b6593ef7dc3170529582e316/ffs-watchdog/files/usr/sbin/ffs-watchdog#L3

warum `-gt 4` ?

wäre nicht besser `pgrep` zu benutzen?

    $(pgrep -f "$ME" | wc -l) -gt 1

**Comment by FFS-Roland** [comment]
Man kann auch pgrep benutzen, muss dann aber auf "-gt 2" prüfen, weil im Shell-Script ein $(...) eine Subshell startet, so dass pgrep den Prozess doppelt sieht. Ob ein "-gt 2" dann verständlicher ist, als das "-gt 4" beim "ps  | grep", wage ich zu bezweifeln.

Gäbe es unter Gluon auch den Parameter -c beim pgrep, hätte ich es gemacht, um die Pipe zu vermeiden.

**Comment by FFS-Roland** [comment]
Korrektur:

Man muss bei pgrep sogar auf "-gt 3" prüfen, weil der cron-Job auch mitzählt.
